spring:
  datasource:
    url: jdbc:postgresql://telegram-db:5432/telebot
    username: telebot
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8090